# Generated by Django 3.1.5 on 2021-09-16 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pop_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop_entry',
            name='condition',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='blank', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pop_entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pop_entry',
            name='image',
            field=models.ImageField(default='blank', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pop_entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
